easyRotation.modules.mmHunt = {}

function easyRotation.modules.mmHunt.init()
  local _,playerClass = UnitClass("player")
  return playerClass == "HUNTER" and GetSpecialization() == 2
end

function easyRotation.modules.mmHunt.initializeVariables()
  if not easyRotationVars.mode then easyRotationVars.mode = "Single Target" end
end

function easyRotation.modules.mmHunt.Slash(cmd,val)
  if (cmd == 'mode' and easyRotationVars.mode == "Single Target") then
    easyRotationVars.mode = "AOE"
    DEFAULT_CHAT_FRAME:AddMessage("easyRotation AOE mode",0,0,1)
    return true
  elseif (cmd == 'mode' and easyRotationVars.mode  == "AOE") then
    easyRotationVars.mode = "Single Target"
    DEFAULT_CHAT_FRAME:AddMessage("easyRotation Single Target mode",0,0,1)
    return true
  else
    return false
  end
end
--Single Target Shot Priority

--The general MM shot/ability priority is as follows for single targets:
--1) Shortly before combat starts apply HUNTERS MARK to the target
--2) Shortly before combat starts cast MISDIRECT on the target’s tank
--3) SERPENT STING (only if the target will live longer than 12s)
--4) CHIMERA SHOT if new target that is not marked to apply MfD or to refresh SrS
--5) AIMED SHOT MMM proc
--6) STEADY SHOT pair if no ISS buff
--7) KILL SHOT
--8) RF
--9) READINESS (RD)
--10) ARCANE SHOT (or KILL COMMAND with T12 4-set proc)/AIMED SHOT hardcast
--11) STEADY SHOT pair (if less than 3 to 4s on the ISS buff)
--12) KILL COMMAND (if have a RiF or pet is on the target and target is out of LoS)
--13) STEADY SHOT

--At the start of fights on premarked targets, if you can start precasting an AI during the pull, then do so. Otherwise, 
--I suggest starting with:
--SrS->RF->AI hardcast->SS pair to get the ISS buff to reduce AI cast times->AI hardcast-> AI hardcast-> Readiness->SS 
--pair->continuing with the standard priority

--I prefer to always start with SrS so I do not have to remember to apply it later and will have it on the target the whole time. 
--It also uses up some focus that will regen during the first AI hardcast. 
--I follow the SrS with RF to speed up the subsequent AI hardcasts and increase focus generation. 
--I prefer to cast the first SS pair to start the ISS buff until after the first AI hardcast since that way 
--I can take advantage of at least some of the focus generated by the SS pair. After the SS pair, 
--I am usually at 100% focus and can follow them with an AI pair, which leaves me low in focus 
--requiring another SS pair to generated enough focus to continue with the normal shot priority.
--When switching targets, I suggest opening with CS if it is off CD to apply the MfD effect to mark the target. 
--If CS is on CD for a while, you can optionally use an AS instead to mark the target.
-- Multiple Target Shot Priority


--The general MM shot/ability priority is as follows for multiple targets:
--1) Shortly before combat starts apply HM to the prime target (can be skipped if not enough time)
--2) Shortly before combat starts cast MD on the main tank for the targets
--3) Shortly before combat starts cast Trap Launcher and then ET 
--4) At the start of combat, place ET where the tank will tank the targets (recast off CD if targets not close to dead yet)
--5) MS (plus the WQ procs)
--6) MMM AI (especially if your current target is about to die for chance of killing blow and 50 focus)
--7) KS (especially if your current target is about to die for chance of killing blow and 50 focus)
--8) SS (to regen focus for more MSs - can do a pair for the ISS buff and better focus regen)
--It usually is not worth it to use RF and Readiness on AoE packs since those are usually trash and you want to make sure to have both 
--ready for boss fights or they are usually adds and you instead prefer to utilize the RFs to improve your single target DPS. 
--However, if it is a really difficult AoE pack of long enough duration, it may be beneficial to use RF and Readiness 
--for the additional focus regen from RF and the faster SS cast times to power more MSs.
--It is also usually not worthwhile to use CS on most multi-target situations. This is because its focus cost (44) is twice 
--that of MS (20) if talented for Bombardment and it is in effect. Furthermore, as shown in the table below, 
--at a little over 4 targets, the MS damage overcomes the CS damage. Considering the extra focus cost of CS, 
--it really is not worth using in AoE situations until you have two or three targets.
--Note that it is currently worthwhile to use the AoE rotation on packs of at least 3 targets. 
--Single target DPS is generally better on packs of size 2, especially when under dynamic haste effects. 
--However, on dual targets while unhasted, it can possibly be better to utilize the multitarget rotation as long as you are 
--talented for Bombardment. This is because when Bombardment is in effect, 
--your MSs casts actually cost less focus (20) than AS (22) and does more damage, especially when factoring in the additional WQ procs, 
--as shown in the table above. The only thing lost by using MS instead of AS is the chance for Sic’Em procs, 
--but the additional hunter damage outweighs the additional pet damage. The one concern with using MS on dual-targets is maintaining 
--the Bombardment buff for the reduced cast cost while also still using CS, MMM AI procs, and cast SS pairs for regen focus. 
--If you are able to maintain the Bombardment buff and still use your high single-target attacks, 
--then using MS instead of AS is worthwhile; otherwise, it is not.
--Also note that the DPS you do on the primary target is considerably higher than the DPS on the other targets due to the autoshots, 
--SSs, MMM AIs, KSs, and extra WQs. Over a long duration AoE battle, the DPS on the primary target can still be more DPS 
--than that on up to another 5 to 6 secondary targets as shown in the table below. On shorter AoE battles where most of the attacks
--are MSs, the percentage of the damage on the primary target is still higher than the secondary targets but a lot closer.
function easyRotation.modules.mmHunt.DecideSpells()

if not easyRotation:UnitHasDebuff("target","Hunter's Mark") 
   and easyRotation:PlayerCanCastSpell("Hunter's Mark",easyRotation.fuzzTime)
   then easyRotation:UpdateButton("Hunter's Mark")
elseif not easyRotation:UnitHasDebuff("target","Serpent Sting")
   and easyRotation:PlayerCanCastSpell("Serpent Sting",easyRotation.fuzzTime)
   then easyRotation:UpdateButton("Serpent Sting")
elseif easyRotation:PlayerCanCastSpell("Chimera Shot",easyRotation.fuzzTime) 
   and not easyRotation:UnitHasDebuffRemaining("target","Serpent Sting") < 3 
   --or easyRotation:UnithasDebuff("Target","Marked for Death")   
   then easyRotation:UpdateButton("Chimera Shot")
elseif not easyRotation:UnitHasBuff("player","Improved Steady Shot") 
   or (easyRotation:UnitHasDebuffRemaining("player","Improved Steady Shot") < 3)
   and easyRotation:PlayerCanCastSpell("Steady Shot",easyRotation.fuzzTime)
   then easyRotation:UpdateButton("Steady Shot")
elseif easyRotation:UnitHealthRemaining("target") < 20
   and easyRotation:PlayerCanCastSpell("Kill Shot",easyRotation.fuzzTime)
   then easyRotation:UpdateButton("Kill Shot")
elseif easyRotation:PlayerCanCastSpell("Rapid Fire",easyRotation.fuzzTime)
   then easyRotation:UpdateButton("Rapid Fire")
elseif easyRotation:PlayerCanCastSpell("Readiness",easyRotation.fuzzTime)
   then easyRotation:UpdateButton("Readiness")
elseif easyRotation:PlayerCanCastSpell("Arcane Shot",easyRotation.fuzzTime)
   then easyRotation:UpdateButton("Arcane Shot")
elseif easyRotation:PlayerCanCastSpell("Aimed Shot",easyRotation.fuzzTime)
   then easyRotation:UpdateButton("Aimed Shot")
elseif easyRotation:PlayerCanCastSpell("Kill Command",easyRotation.fuzzTime)
   then easyRotation:UpdateButton("Kill Command")
 end
end










-- Multiple Target Shot Priority


--The general MM shot/ability priority is as follows for multiple targets:
--1) Shortly before combat starts apply HM to the prime target (can be skipped if not enough time)
--2) Shortly before combat starts cast MD on the main tank for the targets
--3) Shortly before combat starts cast Trap Launcher and then ET 
--4) At the start of combat, place ET where the tank will tank the targets (recast off CD if targets not close to dead yet)
--5) MS (plus the WQ procs)
--6) MMM AI (especially if your current target is about to die for chance of killing blow and 50 focus)
--7) KS (especially if your current target is about to die for chance of killing blow and 50 focus)
--8) SS (to regen focus for more MSs - can do a pair for the ISS buff and better focus regen)
--It usually is not worth it to use RF and Readiness on AoE packs since those are usually trash and you want to make sure to have both 
--ready for boss fights or they are usually adds and you instead prefer to utilize the RFs to improve your single target DPS. 
--However, if it is a really difficult AoE pack of long enough duration, it may be beneficial to use RF and Readiness 
--for the additional focus regen from RF and the faster SS cast times to power more MSs.
--It is also usually not worthwhile to use CS on most multi-target situations. This is because its focus cost (44) is twice 
--that of MS (20) if talented for Bombardment and it is in effect. Furthermore, as shown in the table below, 
--at a little over 4 targets, the MS damage overcomes the CS damage. Considering the extra focus cost of CS, 
--it really is not worth using in AoE situations until you have two or three targets.
--Note that it is currently worthwhile to use the AoE rotation on packs of at least 3 targets. 
--Single target DPS is generally better on packs of size 2, especially when under dynamic haste effects. 
--However, on dual targets while unhasted, it can possibly be better to utilize the multitarget rotation as long as you are 
--talented for Bombardment. This is because when Bombardment is in effect, 
--your MSs casts actually cost less focus (20) than AS (22) and does more damage, especially when factoring in the additional WQ procs, 
--as shown in the table above. The only thing lost by using MS instead of AS is the chance for Sic’Em procs, 
--but the additional hunter damage outweighs the additional pet damage. The one concern with using MS on dual-targets is maintaining 
--the Bombardment buff for the reduced cast cost while also still using CS, MMM AI procs, and cast SS pairs for regen focus. 
--If you are able to maintain the Bombardment buff and still use your high single-target attacks, 
--then using MS instead of AS is worthwhile; otherwise, it is not.
--Also note that the DPS you do on the primary target is considerably higher than the DPS on the other targets due to the autoshots, 
--SSs, MMM AIs, KSs, and extra WQs. Over a long duration AoE battle, the DPS on the primary target can still be more DPS 
--than that on up to another 5 to 6 secondary targets as shown in the table below. On shorter AoE battles where most of the attacks
--are MSs, the percentage of the damage on the primary target is still higher than the secondary targets but a lot closer.

